version: '3.8'

services:
  redis:
    container_name: redis
    image: redis
    build:
      context: .
      dockerfile: deployments/dockerfiles/redis.Dockerfile
  api:
    container_name: api
    build:
      context: .
      dockerfile: deployments/dockerfiles/api.Dockerfile
    depends_on:
      - redis
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: deployments/dockerfiles/celery.Dockerfile
    depends_on:
      - redis
      - api
  flower:
    container_name: flower
    build:
      context: .
      dockerfile: deployments/dockerfiles/flower.Dockerfile
    depends_on:
      - api
      - redis
      - celery
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: deployments/dockerfiles/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - redis
      - celery
      - flower